[project]
name = "2025-09-15-tvdi"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.2",
    "ipykernel>=6.30.1",
    "requests>=2.32.5",
]
